### ISSUE TITLE
Filtering of exactly same question

### ISSUE THREAD

**Issue by ketchisauplb** [neilmarion/paano#68]
![same question](https://f.cloud.github.com/assets/4350651/465683/93b812c4-b63d-11e2-816a-5efc5faae715.jpg)

Two exactly same questions done in different time. 
showing as two different question
Possible solution:
1. Auto filter the next question ./ auto disable same questions
2. Auto route the second question to the first question

**Comment by neilmarion** [comment]
We shoud permit users to ask a question even if they asked an almost the same question (in terms of syntax or semantics) to the one's existing. Information flow must be continuous. There should just be (future feature) where some users, most probably admins or high-reputation users or maybe regular users, has the ability to flag a question as a duplicate. There's routing, but auto-routing is impossible/hard because because one question maybe duplicates of so many questions.

See this feature from Stackoverflow: http://stackoverflow.com/questions/8305352/computing-all-the-possible-substrings-of-a-given-string
